### ISSUE TITLE
DPS stops being picked up after some fights

### ISSUE THREAD

**Issue by Owyn** [neowutran/ShinraMeter#261]
after some BAM\Boss fightings chat functions work etc but no new dps is being picked up, only old statistics about old BAMS\bosses stay

**Comment by Gl0** [comment]
Check error.log for missing packets debug

**Comment by Owyn** [comment]
error.log is 0 bytes

**Comment by Gl0** [comment]
"chat functions work" = you receive fresh notifications and see new messages in chat window?

**Comment by Owyn** [comment]
yes

**Comment by Gl0** [comment]
Hm... don't see the way other than missing packet with target spawn.

**Comment by Owyn** [comment]
I start shinra, start tera, play dungeons on one character, kill BAMS, switch to another character, do the same, then I notice in some dungeon it just doesn't pick up new DPS statistics (usually I notice it in channelworks), only old stay, reset doesn't help - data would just stay empty

**Comment by Owyn** [comment]
> Hm... don't see the way other than missing packet with target spawn.

It stops at all, like even when I run 10 new bosses - noone is picked for DPS statistics

**Comment by Gl0** [comment]
Do you receive missing buff notifications?

**Comment by Owyn** [comment]
> Do you receive missing buff notifications?

No, boss enrage event doesn't work too,

just happened again, 1st boss in Lilith normal worked fine: http://moongourd.com/ru/encounter?area=769&boss=76901&log=5841acdc35e03

but no data about 2nd+ boss was picked, so it just stopped working

looks like chat stopped working too, pm notifications and chat at all, here's a screen, it's 20:33 and i'm still in game but all data stopped being picked up at 20:19
![6 _proc](https://cloud.githubusercontent.com/assets/1309656/20843988/c4d70774-b8ce-11e6-8788-fbfef9af5099.png)

**Comment by Gl0** [comment]
You are using raw sockets or npcap?

**Comment by Owyn** [comment]
raw sockets, windows firewall disabled, no other firewalls

**Comment by Gl0** [comment]
We have debug only for missing packets, but meter can receive bad packet, that may cause message splitter to lost sync with actual messages.
It's better to use npcap than raw sockets, cause it have kernel level filters that drastically decrease amount of data passed to user mode for parsing, and therefor lower number of possible errors and resources usage.

**Comment by snwFlake** [comment]
@Owyn do you use the ShinraLauncher?

**Comment by Owyn** [comment]
@snwFlake I launch the program via ShinraMeter.exe

**Comment by Gl0** [comment]
When meter stops working - does it start working again if you restart tera (or go to server select screen and back)?

**Comment by Owyn** [comment]
> When meter stops working - does it start working again if you restart tera (or go to server select screen and back)?

I always restart the meter along with the game so it would start working again, so I should keep meter running without restarts but only restart the game?

**Comment by Gl0** [comment]
yes, try it - that would show, whether it's lost of sync due to packet corruption or some other case.

**Comment by Owyn** [comment]
@Gl0
tried it several times - meter doesn't start picking any date after server reentering, it's jammed for good

**Comment by Gl0** [comment]
In that case - we messed something with event system. In next version there are a lot of changes in event logic, may be that issue is already fixed. Probably we release it tomorrow with KR update.

**Comment by Owyn** [comment]
I tried unchecking "enable events and chat functions" in settings but it didn't help, still gets stuck sometimes

**Comment by Gl0** [comment]
Do you have this issue in 1.65? And is there anything new in error.log (I've added some more debug)

**Comment by Owyn** [comment]
Yes, it's still present in 1.65, just happened in some battleground fight, error.log doesn't have info for that time when it happened, just this yesterday stuff when all worked fine:

```
2016-12-13 22:25:38,718 [28] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8217612 VFree:7740152 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:24% Received: 67613348
67613390: 44
Queue length:501
New Queue length:501
Skipping bytes:42
2016-12-13 22:25:55,324 [16] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8234104 VFree:7758872 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:35% Received: 67617128
67617149: 21
Queue length:501
New Queue length:501
Skipping bytes:21
2016-12-13 22:25:56,360 [33] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8227272 VFree:7752896 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:60% Received: 67617170
67617256: 44
Queue length:501
New Queue length:501
Skipping bytes:86
2016-12-13 22:25:57,467 [10] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8229708 VFree:7747656 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:52% Received: 67617344
67617381: 40
Queue length:501
New Queue length:501
Skipping bytes:37
2016-12-13 22:25:58,519 [16] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8228560 VFree:7749440 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:38% Received: 67617449
67617470: 44
Queue length:501
New Queue length:501
Skipping bytes:21
2016-12-13 22:26:01,626 [33] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8504732 VFree:8030528 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:38% Received: 67619241
67619371: 21
Queue length:501
New Queue length:501
Skipping bytes:130
2016-12-13 22:26:02,660 [12] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8505084 VFree:8026584 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:38% Received: 67619413
67619455: 50
Queue length:501
New Queue length:501
Skipping bytes:42
2016-12-13 22:26:12,032 [28] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8513652 VFree:8038348 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:29% Received: 67620844
67620909: 44
Queue length:501
New Queue length:501
Skipping bytes:65
2016-12-13 22:26:18,476 [33] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8521784 VFree:8041216 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:43% Received: 67622381
67622402: 40
Queue length:501
New Queue length:501
Skipping bytes:21
2016-12-13 22:26:19,517 [36] ERROR ShinraMeter [(null)] - ##### (version=1.65):
##### Debug: Low priority NetworkSniffer.IpSnifferRawSocketMultipleInterfaces running on win 10.0.14393 Memory Total:16695788 Virtual:16695788 PhFree:8516720 VFree:8040444 CPU:Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz load:54% Received: 67622644
67622696: 21
Queue length:501
New Queue length:501
Skipping bytes:52

```

**Comment by Owyn** [comment]
I'm using npcap for 3+ days and no such bug happened since then even though I keep shinrameter opened all the time, so you're right, this must be something to do with non-tera packets
